### ISSUE TITLE
Where are the binaries?

### ISSUE THREAD

**Issue by justingoldberg** [samizzo/hexed#4]
Where are the binaries?

**Comment by samizzo** [comment]
It looks like Appveyor expired the last build and deleted it. I set up Appveyor to do a release which you can get from here: https://github.com/samizzo/hexed/releases

Currently it's just the 64-bit build. If you want 32-bit let me know!

**Comment by justingoldberg** [comment]
I'm good, thanks!

**Comment by wenmin92** [comment]
I [put](https://github.com/ScoopInstaller/Main/pull/681) this app on the Main [scoop](https://scoop.sh/) bucket, when merged, we can install this app by: 
```
scoop install hexed
```

**Comment by samizzo** [comment]
Thanks!
